export default interface IUser {
  login: string,
  id: number,
  url: string,
  avatar_url: string,
  gravatar_id: string,
  followers_url: string,
  following_url:string,
  gists_url: string,
  starred_url: string,
  subscriptions_url: string,
  organizations_url: string,
  repos_url: string,
  name: string,
  company: string,
  blog: string,
  location: string,
  email: string,
  bio: string,
  public_repos: number,
  public_gists: number,
  followers: number,
  following: number,
  created_at: string,
  updated_at: string
}
